### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by gunnicus** [EmerickH/AlexaPiWrapper#1]
Hi,

I'm getting an error:
The request was aborted: Could not create SSL/TLS secure channel
 
So I added these 2 lines under download_DoWork 
ServicePointManager.Expect100Continue = True
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

**Comment by EmerickH** [comment]
This repo is no more maintained since AlexaPi-Windows is fused with base AlexaPi: https://github.com/alexa-pi/AlexaPi
